include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    collection_methods_unrelated_type: ignore
    deprecated_member_use_from_same_package: ignore
    library_private_types_in_public_api: ignore
    non_constant_identifier_names: ignore
    use_build_context_synchronously: ignore
