name: inventory
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  awesome_dialog: ^3.2.1
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/



flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Medium.ttf
      